# -*- coding: utf-8 -*-
import json
import logging
import re

from odoo import models, fields, api, _
from odoo.exceptions import UserError

_logger = logging.getLogger(__name__)

PRIORITY_SELECTION = [
    ('0', 'Low'),
    ('1', 'Normal'),
    ('2', 'High'),
    ('3', 'Urgent'),
]

SENTIMENT_SELECTION = [
    ('positive', 'Positive'),
    ('neutral', 'Neutral'),
    ('negative', 'Negative'),
]


class HelpdeskTicket(models.Model):
    _name = 'ollama.helpdesk.ticket'
    _description = 'Helpdesk Ticket'
    _inherit = ['mail.thread', 'mail.activity.mixin', 'ollama.mixin']
    _order = 'priority desc, create_date desc'

    # ------------------------------------------------------------------
    # Core fields
    # ------------------------------------------------------------------
    name = fields.Char(
        string='Subject', required=True, tracking=True,
        index='trigram',
    )
    description = fields.Html(string='Description')
    partner_id = fields.Many2one(
        'res.partner', string='Customer', tracking=True,
        index=True,
    )
    user_id = fields.Many2one(
        'res.users', string='Assigned to', tracking=True,
        index=True,
    )
    stage_id = fields.Many2one(
        'ollama.helpdesk.stage', string='Stage', tracking=True,
        group_expand='_read_group_stage_ids',
        default=lambda self: self._default_stage_id(),
        index=True,
    )
    priority = fields.Selection(
        PRIORITY_SELECTION, string='Priority', default='1', tracking=True,
        index=True,
    )
    kanban_state = fields.Selection([
        ('normal', 'In Progress'),
        ('done', 'Ready'),
        ('blocked', 'Blocked'),
    ], string='Kanban State', default='normal', tracking=True)

    # ------------------------------------------------------------------
    # AI fields (readonly, populated by AI actions)
    # ------------------------------------------------------------------
    ai_classification = fields.Char(
        string='AI Classification', readonly=True, copy=False,
        help="Category automatically assigned by AI analysis.",
    )
    ai_priority_suggestion = fields.Selection(
        PRIORITY_SELECTION, string='AI Priority Suggestion', readonly=True,
        copy=False,
        help="Priority level suggested by AI based on ticket content.",
    )
    ai_draft_response = fields.Html(
        string='AI Draft Response', readonly=True, copy=False,
        help="Draft response generated by AI for this ticket.",
    )
    ai_sentiment = fields.Selection(
        SENTIMENT_SELECTION, string='AI Sentiment', readonly=True, copy=False,
        help="Customer sentiment detected by AI analysis.",
    )
    ai_analysis_date = fields.Datetime(
        string='AI Analysis Date', readonly=True, copy=False,
    )

    # ------------------------------------------------------------------
    # Computed / display
    # ------------------------------------------------------------------
    is_closed = fields.Boolean(
        string='Is Closed', compute='_compute_is_closed', store=True,
    )

    @api.depends('stage_id', 'stage_id.is_closing')
    def _compute_is_closed(self):
        for ticket in self:
            ticket.is_closed = ticket.stage_id.is_closing if ticket.stage_id else False

    # ------------------------------------------------------------------
    # Defaults
    # ------------------------------------------------------------------
    def _default_stage_id(self):
        return self.env['ollama.helpdesk.stage'].search([], order='sequence, id', limit=1).id

    # ------------------------------------------------------------------
    # Kanban group expand
    # ------------------------------------------------------------------
    @api.model
    def _read_group_stage_ids(self, stages, domain):
        """Return all stages so they all appear in kanban even when empty."""
        return self.env['ollama.helpdesk.stage'].search([], order='sequence, id')

    # ------------------------------------------------------------------
    # AI: Classify ticket
    # ------------------------------------------------------------------
    def action_classify_ticket(self):
        """Use AI to classify the ticket: category, priority, sentiment."""
        self.ensure_one()
        # Build a plain-text version of the description
        description_text = ''
        if self.description:
            description_text = re.sub(r'<[^>]+>', ' ', self.description)
            description_text = re.sub(r'\s+', ' ', description_text).strip()

        if not self.name and not description_text:
            raise UserError(_("Please provide a subject or description before classifying."))

        system_prompt = (
            "You are a helpdesk ticket classifier. Analyze the ticket and respond "
            "with ONLY a JSON object, no other text. The JSON must have exactly "
            "these keys:\n"
            '- "classification": a short category string (e.g. "Technical Issue", '
            '"Billing", "Feature Request", "Account", "Bug Report", "General Inquiry")\n'
            '- "priority": an integer 0-3 where 0=Low, 1=Normal, 2=High, 3=Urgent\n'
            '- "sentiment": one of "positive", "neutral", or "negative"\n'
        )

        prompt = (
            f"Classify this helpdesk ticket:\n\n"
            f"Subject: {self.name or 'N/A'}\n"
            f"Description: {description_text or 'N/A'}\n\n"
            f"Respond with ONLY the JSON object."
        )

        result = self._call_ollama_safe(
            prompt,
            system_prompt=system_prompt,
            temperature=0.3,
            max_tokens=300,
            log_model=self._name,
            log_res_id=self.id,
        )

        if not result:
            raise UserError(_("AI did not return a response. Check your AI configuration."))

        data = self._parse_json_response(result)
        if not data or not isinstance(data, dict):
            raise UserError(_(
                "AI returned an unexpected format. Raw response:\n%s"
            ) % result[:500])

        vals = {'ai_analysis_date': fields.Datetime.now()}

        # Classification
        classification = data.get('classification', '')
        if classification:
            vals['ai_classification'] = str(classification)[:100]

        # Priority
        priority = data.get('priority')
        if priority is not None:
            priority_str = str(int(priority)) if isinstance(priority, (int, float)) else str(priority)
            if priority_str in ('0', '1', '2', '3'):
                vals['ai_priority_suggestion'] = priority_str

        # Sentiment
        sentiment = data.get('sentiment', '')
        if sentiment in ('positive', 'neutral', 'negative'):
            vals['ai_sentiment'] = sentiment

        self.write(vals)

        return {
            'type': 'ir.actions.client',
            'tag': 'display_notification',
            'params': {
                'title': _('AI Classification Complete'),
                'message': _('Category: %s | Priority: %s | Sentiment: %s') % (
                    vals.get('ai_classification', 'N/A'),
                    dict(PRIORITY_SELECTION).get(vals.get('ai_priority_suggestion', ''), 'N/A'),
                    vals.get('ai_sentiment', 'N/A').capitalize(),
                ),
                'type': 'success',
                'sticky': False,
            }
        }

    # ------------------------------------------------------------------
    # AI: Generate response
    # ------------------------------------------------------------------
    def action_generate_response(self):
        """Use AI to draft a helpful customer response."""
        self.ensure_one()

        description_text = ''
        if self.description:
            description_text = re.sub(r'<[^>]+>', ' ', self.description)
            description_text = re.sub(r'\s+', ' ', description_text).strip()

        # Gather recent chatter messages for context
        messages_text = ''
        messages = self.env['mail.message'].search([
            ('res_id', '=', self.id),
            ('model', '=', self._name),
            ('message_type', 'in', ('comment', 'email')),
        ], order='date desc', limit=10)
        if messages:
            parts = []
            for msg in reversed(messages):
                author = msg.author_id.name or 'Unknown'
                body = re.sub(r'<[^>]+>', ' ', msg.body or '')
                body = re.sub(r'\s+', ' ', body).strip()
                if body:
                    parts.append(f"[{author}]: {body}")
            if parts:
                messages_text = '\n'.join(parts)

        system_prompt = (
            "You are a professional and empathetic helpdesk agent. Draft a helpful, "
            "clear, and friendly response to the customer's ticket. "
            "Be solution-oriented. If you don't have enough information to solve "
            "the issue, ask clarifying questions politely. "
            "Format the response as clean HTML suitable for an email (use <p> tags "
            "for paragraphs, <ul>/<li> for lists if needed). "
            "Do NOT include a subject line. Start directly with the greeting."
        )

        prompt = f"Ticket Subject: {self.name or 'N/A'}\n"
        prompt += f"Customer: {self.partner_id.name or 'Unknown'}\n"
        if self.ai_classification:
            prompt += f"Category: {self.ai_classification}\n"
        if self.ai_sentiment:
            prompt += f"Sentiment: {self.ai_sentiment}\n"
        prompt += f"\nDescription:\n{description_text or 'N/A'}\n"
        if messages_text:
            prompt += f"\nConversation history:\n{messages_text}\n"
        prompt += (
            "\nDraft a professional response to help this customer. "
            "Respond with the HTML body only."
        )

        result = self._call_ollama_safe(
            prompt,
            system_prompt=system_prompt,
            temperature=0.7,
            max_tokens=1500,
            log_model=self._name,
            log_res_id=self.id,
        )

        if not result:
            raise UserError(_("AI did not return a response. Check your AI configuration."))

        # Ensure result is wrapped in HTML paragraph tags if not already
        result_clean = result.strip()
        if not result_clean.startswith('<'):
            result_clean = '<p>' + result_clean.replace('\n\n', '</p><p>').replace('\n', '<br/>') + '</p>'

        self.write({
            'ai_draft_response': result_clean,
            'ai_analysis_date': fields.Datetime.now(),
        })

        return {
            'type': 'ir.actions.client',
            'tag': 'display_notification',
            'params': {
                'title': _('AI Response Generated'),
                'message': _('A draft response has been generated. Review it in the AI Draft Response tab.'),
                'type': 'success',
                'sticky': False,
            }
        }

    # ------------------------------------------------------------------
    # AI: Send AI response
    # ------------------------------------------------------------------
    def action_send_ai_response(self):
        """Post the AI draft response as a message on the ticket thread."""
        self.ensure_one()
        if not self.ai_draft_response:
            raise UserError(_("No AI draft response to send. Generate one first."))

        self.message_post(
            body=self.ai_draft_response,
            message_type='comment',
            subtype_xmlid='mail.mt_comment',
        )

        return {
            'type': 'ir.actions.client',
            'tag': 'display_notification',
            'params': {
                'title': _('Response Sent'),
                'message': _('The AI draft response has been posted to the ticket.'),
                'type': 'success',
                'sticky': False,
            }
        }

    # ------------------------------------------------------------------
    # AI: Apply AI priority suggestion
    # ------------------------------------------------------------------
    def action_apply_ai_priority(self):
        """Apply the AI-suggested priority to the ticket."""
        self.ensure_one()
        if not self.ai_priority_suggestion:
            raise UserError(_("No AI priority suggestion available. Classify the ticket first."))
        self.priority = self.ai_priority_suggestion
        return {
            'type': 'ir.actions.client',
            'tag': 'display_notification',
            'params': {
                'title': _('Priority Updated'),
                'message': _('Priority set to: %s') % dict(PRIORITY_SELECTION).get(self.priority, ''),
                'type': 'success',
                'sticky': False,
            }
        }
