# -*- coding: utf-8 -*-
import json
import logging

from odoo import models, fields, api, _
from odoo.exceptions import UserError

_logger = logging.getLogger(__name__)


class ProductTemplate(models.Model):
    _inherit = ['product.template', 'ollama.mixin']

    # ------------------------------------------------------------------
    # AI SEO Fields
    # ------------------------------------------------------------------
    ai_seo_score = fields.Integer(
        string='SEO Score',
        readonly=True,
        help='AI-assessed SEO score from 0 to 100',
    )
    ai_seo_title = fields.Char(
        string='SEO Meta Title',
        size=70,
        readonly=True,
        help='AI-generated meta title (max 60 characters recommended)',
    )
    ai_seo_description = fields.Text(
        string='SEO Meta Description',
        readonly=True,
        help='AI-generated meta description (max 160 characters recommended)',
    )
    ai_seo_keywords = fields.Char(
        string='SEO Keywords',
        size=500,
        readonly=True,
        help='Comma-separated keywords generated by AI',
    )
    ai_seo_suggestions = fields.Text(
        string='SEO Suggestions',
        readonly=True,
        help='AI improvement suggestions for better SEO ranking',
    )
    ai_seo_date = fields.Datetime(
        string='Last SEO Generation',
        readonly=True,
        help='Date and time of last AI SEO generation',
    )

    # ------------------------------------------------------------------
    # Generate SEO
    # ------------------------------------------------------------------
    def action_generate_seo(self):
        """Generate SEO metadata for the current product using AI."""
        self.ensure_one()
        if not self.name:
            raise UserError(_('Product must have a name before generating SEO.'))

        config = self._get_ollama_config()

        # Build product context
        category_name = self.categ_id.complete_name if self.categ_id else 'N/A'
        description = ''
        if hasattr(self, 'description_sale') and self.description_sale:
            description = self.description_sale
        elif hasattr(self, 'description') and self.description:
            description = self.description

        prompt = (
            "You are an expert SEO specialist for e-commerce websites. "
            "Analyze the following product and generate optimized SEO metadata.\n\n"
            "Product Information:\n"
            f"- Name: {self.name}\n"
            f"- Category: {category_name}\n"
            f"- Price: {self.list_price}\n"
            f"- Description: {description or 'No description available'}\n\n"
            "Generate a JSON object with exactly these keys:\n"
            "{\n"
            '  "meta_title": "optimized meta title, max 60 characters",\n'
            '  "meta_description": "compelling meta description, max 160 characters",\n'
            '  "keywords": ["keyword1", "keyword2", "keyword3", ...],\n'
            '  "seo_score": 75,\n'
            '  "suggestions": ["suggestion 1", "suggestion 2", ...]\n'
            "}\n\n"
            "Rules:\n"
            "- meta_title must be under 60 characters and include the product name\n"
            "- meta_description must be under 160 characters and be action-oriented\n"
            "- Provide 5-10 relevant keywords\n"
            "- seo_score is your assessment from 0-100 of the product's SEO readiness\n"
            "- Provide 2-5 actionable suggestions to improve SEO\n"
            "- Return ONLY valid JSON, no other text"
        )

        response = self._call_ollama_safe(
            prompt,
            system_prompt='You are an SEO expert. Always respond with valid JSON only.',
            log_model=self._name,
            log_res_id=self.id,
        )

        if not response:
            return {
                'type': 'ir.actions.client',
                'tag': 'display_notification',
                'params': {
                    'title': _('SEO Generation Failed'),
                    'message': _('Could not get a response from the AI. '
                                 'Please check your Ollama configuration.'),
                    'type': 'danger',
                    'sticky': False,
                },
            }

        data = self._parse_json_response(response)
        if not data:
            return {
                'type': 'ir.actions.client',
                'tag': 'display_notification',
                'params': {
                    'title': _('SEO Generation Failed'),
                    'message': _('Could not parse the AI response as JSON. '
                                 'Please try again.'),
                    'type': 'warning',
                    'sticky': False,
                },
            }

        # Extract and write fields
        keywords = data.get('keywords', [])
        if isinstance(keywords, list):
            keywords = ', '.join(str(k) for k in keywords)

        suggestions = data.get('suggestions', [])
        if isinstance(suggestions, list):
            suggestions = '\n'.join(f'- {s}' for s in suggestions)

        seo_score = data.get('seo_score', 0)
        try:
            seo_score = int(seo_score)
            seo_score = max(0, min(100, seo_score))
        except (ValueError, TypeError):
            seo_score = 0

        self.write({
            'ai_seo_title': (data.get('meta_title') or '')[:70],
            'ai_seo_description': (data.get('meta_description') or '')[:160],
            'ai_seo_keywords': (keywords or '')[:500],
            'ai_seo_score': seo_score,
            'ai_seo_suggestions': suggestions or '',
            'ai_seo_date': fields.Datetime.now(),
        })

        return {
            'type': 'ir.actions.client',
            'tag': 'display_notification',
            'params': {
                'title': _('SEO Generated'),
                'message': _("SEO metadata generated for '%s' — Score: %d/100") % (
                    self.name, seo_score),
                'type': 'success',
                'sticky': False,
            },
        }

    # ------------------------------------------------------------------
    # Apply SEO to Website
    # ------------------------------------------------------------------
    def action_apply_seo(self):
        """Copy AI-generated SEO fields to the standard website meta fields."""
        self.ensure_one()

        vals = {}
        if self.ai_seo_title:
            vals['website_meta_title'] = self.ai_seo_title
        if self.ai_seo_description:
            vals['website_meta_description'] = self.ai_seo_description

        if not vals:
            return {
                'type': 'ir.actions.client',
                'tag': 'display_notification',
                'params': {
                    'title': _('Nothing to Apply'),
                    'message': _('No AI SEO data available. '
                                 'Please generate SEO first.'),
                    'type': 'warning',
                    'sticky': False,
                },
            }

        self.write(vals)
        return {
            'type': 'ir.actions.client',
            'tag': 'display_notification',
            'params': {
                'title': _('SEO Applied'),
                'message': _("Website meta fields updated for '%s'.") % self.name,
                'type': 'success',
                'sticky': False,
            },
        }

    # ------------------------------------------------------------------
    # Audit SEO
    # ------------------------------------------------------------------
    def action_audit_seo(self):
        """Audit existing SEO data and provide a score with suggestions."""
        self.ensure_one()

        config = self._get_ollama_config()

        # Gather current SEO state
        current_title = ''
        current_description = ''
        if hasattr(self, 'website_meta_title'):
            current_title = self.website_meta_title or ''
        if hasattr(self, 'website_meta_description'):
            current_description = self.website_meta_description or ''

        category_name = self.categ_id.complete_name if self.categ_id else 'N/A'

        prompt = (
            "You are an expert SEO auditor for e-commerce websites. "
            "Audit the following product's SEO and provide a detailed assessment.\n\n"
            "Product Information:\n"
            f"- Name: {self.name}\n"
            f"- Category: {category_name}\n"
            f"- Price: {self.list_price}\n"
            f"- Current Meta Title: {current_title or 'NOT SET'}\n"
            f"- Current Meta Description: {current_description or 'NOT SET'}\n"
            f"- Has Product Description: {'Yes' if self.description_sale else 'No'}\n"
            f"- Has Images: {'Yes' if self.image_1920 else 'No'}\n\n"
            "Respond with a JSON object:\n"
            "{\n"
            '  "seo_score": 45,\n'
            '  "suggestions": [\n'
            '    "Add a meta title under 60 characters",\n'
            '    "Write a compelling meta description under 160 characters",\n'
            '    ...\n'
            "  ]\n"
            "}\n\n"
            "Score criteria:\n"
            "- Meta title present and under 60 chars: +20 points\n"
            "- Meta description present and under 160 chars: +20 points\n"
            "- Product description filled: +20 points\n"
            "- Product images present: +15 points\n"
            "- Category properly set: +10 points\n"
            "- Good keyword usage: +15 points\n"
            "- Return ONLY valid JSON, no other text"
        )

        response = self._call_ollama_safe(
            prompt,
            system_prompt='You are an SEO auditor. Always respond with valid JSON only.',
            log_model=self._name,
            log_res_id=self.id,
        )

        if not response:
            return {
                'type': 'ir.actions.client',
                'tag': 'display_notification',
                'params': {
                    'title': _('Audit Failed'),
                    'message': _('Could not get a response from the AI.'),
                    'type': 'danger',
                    'sticky': False,
                },
            }

        data = self._parse_json_response(response)
        if not data:
            return {
                'type': 'ir.actions.client',
                'tag': 'display_notification',
                'params': {
                    'title': _('Audit Failed'),
                    'message': _('Could not parse the AI audit response.'),
                    'type': 'warning',
                    'sticky': False,
                },
            }

        seo_score = data.get('seo_score', 0)
        try:
            seo_score = int(seo_score)
            seo_score = max(0, min(100, seo_score))
        except (ValueError, TypeError):
            seo_score = 0

        suggestions = data.get('suggestions', [])
        if isinstance(suggestions, list):
            suggestions = '\n'.join(f'- {s}' for s in suggestions)

        self.write({
            'ai_seo_score': seo_score,
            'ai_seo_suggestions': suggestions or '',
            'ai_seo_date': fields.Datetime.now(),
        })

        return {
            'type': 'ir.actions.client',
            'tag': 'display_notification',
            'params': {
                'title': _('SEO Audit Complete'),
                'message': _("Audit for '%s' — Score: %d/100") % (
                    self.name, seo_score),
                'type': 'success',
                'sticky': False,
            },
        }
