{
    'name': 'PrestaShop Product Sync',
    'version': '18.0.4.2.0',
    'category': 'Sales/Sales',
    'summary': 'Bidirectional PrestaShop product sync: import with preview, export with queue, stock/price push, variant support, anti-duplicate, field mapping, dashboard',
    'author': 'Antigravity',
    'depends': ['prestashop_odoo_sync', 'product', 'stock', 'account', 'bus'],
    'data': [
        'security/ir.model.access.csv',
        'data/ir_cron_data.xml',
        'views/prestashop_product_preview_views.xml',
        'views/prestashop_field_mapping_views.xml',
        'views/prestashop_export_queue_views.xml',
        'views/prestashop_export_log_views.xml',
        'wizard/prestashop_product_sync_wizard_views.xml',
        'wizard/prestashop_reimport_wizard_views.xml',
        'wizard/prestashop_cleanup_wizard_views.xml',
        'wizard/views/prestashop_export_wizard_views.xml',
        'views/prestashop_instance_views.xml',
        'views/product_template_views.xml',
        'views/prestashop_product_dashboard_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'prestashop_product_sync/static/src/js/product_preview_list.js',
        ],
    },
    'installable': True,
    'application': False,
    'license': 'LGPL-3',
}
