# -*- coding: utf-8 -*-
{
    "name": "Planète PIM - Overview",
    "summary": "Vue d’ensemble des fournisseurs, planification et import produits (kanban + wizard).",
    "version": "18.0.2.11.0",
    "author": "Doscaal",
    "license": "LGPL-3",
    "website": "",
    "category": "Tools",
    "depends": [
        "base",
        "product",
        "stock",
        "purchase",
        "product_brand",
        "ftp_tariff_import",
    ],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "views/overview_views.xml",
        "views/file_import_wizard_views.xml",
        "views/staging_views.xml",
        "views/planification_views.xml",
        "views/provider_inherit.xml",
        "views/job_views.xml",
        "views/brand_pending_views.xml",
        "views/brand_alias_history_views.xml",
        "views/colbee_views.xml",
        "views/product_views.xml",
        "views/menuitems.xml",
        "views/planning_views.xml",
        "wizards/staging_delete_wizard_view.xml",
        "data/planete_pim_cron.xml",
    ],
    "installable": True,
    "application": True,
}
